# ── Davao City Government Theme ───────────────────────────────
# Based on the City Government of Davao official branding
# Deep blue and gold color scheme

# Primary: Davao City Blue
PRIMARY_COLOR = "#003366"
PRIMARY_HOVER = "#002244"
PRIMARY_LIGHT = "#E8F0FE"

# Accent: Government Gold
ACCENT_COLOR = "#DAA520"
ACCENT_HOVER = "#B8860B"

# Status colors
DANGER_COLOR = "#C62828"
DANGER_HOVER = "#B71C1C"

WARNING_COLOR = "#E65100"
WARNING_HOVER = "#BF360C"

SUCCESS_COLOR = "#2E7D32"

# Backgrounds
BG_COLOR = "#F0F2F5"
SIDEBAR_BG = "#0A1929"
SIDEBAR_TEXT = "#B0BEC5"
SIDEBAR_HOVER = "#1A3A5C"
SIDEBAR_ACTIVE = "#DAA520"

CARD_BG = "#FFFFFF"
CARD_BORDER = "#D0D5DD"

# Text
TEXT_PRIMARY = "#1A1A2E"
TEXT_SECONDARY = "#5F6368"
TEXT_LIGHT = "#FFFFFF"

# Header
HEADER_BG = "#003366"
HEADER_BORDER = "#002244"

# Table
TABLE_HEADER_BG = "#E8F0FE"
TABLE_ROW_HOVER = "#F5F7FA"
TABLE_BORDER = "#D0D5DD"

# Typography
FONT_FAMILY = "Segoe UI"
FONT_SIZE_SMALL = 11
FONT_SIZE_NORMAL = 13
FONT_SIZE_LARGE = 16
FONT_SIZE_TITLE = 20
FONT_SIZE_HEADER = 24

# Spacing
PADDING_SMALL = 5
PADDING_NORMAL = 10
PADDING_LARGE = 20
PADDING_XLARGE = 30

# Layout
SIDEBAR_WIDTH = 230
SIDEBAR_COLLAPSED_WIDTH = 60
